matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.6.2
    - os: osx
      sudo: required
    - os: windows
      language: python
      sudo: required
      python: 3.6.2
addons:
  chrome: stable
before_script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sh -e /etc/init.d/xvfb start ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sleep 3  ; fi
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 ; fi
  - python3 -V
  - pip3 -V
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - sudo chmod +x jadx/bin/jadx
  - python3 main.py test-apk.apk # or py.test for Python versions 3.5 and below
