matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 3.6.2
    - os: osx
      sudo: required
    - os: windows
      sudo: required
      python: 3.6.2

language: python
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then brew install python3 ; fi
  - python3 -V
  - pip3 -V
# command to install dependencies
install:
  - pip3 install -r requirements.txt
# command to run tests
script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then sudo chmod +x jadx/bin/jadx          ; fi
  - python3 main.py test-apk.apk # or py.test for Python versions 3.5 and below
